### ISSUE TITLE
AttributeError: 'EpsilonGreedy' object has no attribute 'kgoal_space'

### ISSUE THREAD

**Issue by CongryLi** [UT-Austin-RPL/amago#61]
I follow the installation instruction and successfully installed POPgym env.

When I try to run the following command :
python 02_popgym_suite.py --env AutoencodeMedium --parallel_actors 24 --trials 3 --epochs 650 --dset_max_size 80_000 --memory_layers 3 --memory_size 256 --run_name testpopgym --buffer_dir ./buffer

Here is a problem:
./amago/amago/utils.py:31: UserWarning: Missing FlashAttention (2.0) Install
  warnings.warn(colored(f"{msg}", "green"), category=category)
Traceback (most recent call last):
  File "/home/licr8/amago/examples/02_popgym_suite.py", line 77, in <module>
    experiment.start()
  File "/home/licr8/amago/amago/learning.py", line 109, in start
    self.init_envs()
  File "/home/licr8/amago/amago/learning.py", line 214, in init_envs
    self.train_envs = Par(make_train)
  File "/home/licr8/anaconda3/envs/amago/lib/python3.10/site-packages/gymnasium/vector/async_vector_env.py", line 144, in __init__
    dummy_env = env_fns[0]()
  File "/home/licr8/amago/amago/envs/env_utils.py", line 530, in __call__
    env = SequenceWrapper(
  File "/home/licr8/amago/amago/envs/env_utils.py", line 398, in __init__
    "goal": self.env.kgoal_space,
AttributeError: 'EpsilonGreedy' object has no attribute 'kgoal_space'

How can I deal with it ? Expect any response sincerely.

**Comment by jakegrigsby** [comment]
Hi @CongryLi, this is a `gymnasium` version control error created by breaking changes in the big `gymnasium` 1.0 release. AMAGO needs version <= 0.29 (and probably always will because of changes in async env resets). 

An update to the repo (#51) that is about to be merged fixes the gymnasium versioning during installation.

**Comment by CongryLi** [comment]
Thanks a lot @jakegrigsby , the prolem is solved when fix `gymnasium` and `torch` version to 0.26.1 and 2.0 respectively.
